version: 2.1

jobs:
  test:
    docker:
      - image: reactnativecommunity/react-native-android:latest
    steps:
      - checkout  # Check out your source code
      
      - run:
          name: Install dependencies
          command: |
            npm install
          
      - run:
          name: Run ESLint
          command: |
            npx eslint . --max-warnings=0  # Lint all files and fail the build if there are warnings

      - run:
          name: Run ESLint --fix
          command: |
            npx eslint . --fix  # Automatically fix fixable ESLint issues
      
      - run:
          name: Run Prettier
          command: |
            npx prettier --write .  # Format all files with Prettier

workflows:
  version: 2
  linting:
    jobs:
      - test
